### ISSUE TITLE
Evaluating the change from semantic-release to changelogen

### ISSUE THREAD

**Issue by amtins** [SRGSSR/pillarbox-web#166]
`As a Pillarbox developer`, I'd like to know if `changelogen` can be used instead of `semantic-release` to potentially remove a number of development dependencies.

## Acceptance Criteria

- use [`changelogen`](https://www.npmjs.com/package/changelogen)
- remove all `semantic-release` dependencies

**Comment by jboix** [comment]
This what a changelog looks like without any customization:

[CHANGELOG.md](https://github.com/SRGSSR/pillarbox-web/files/13874579/CHANGELOG.md)

**Comment by jboix** [comment]
I've made a test in a [forked project](https://github.com/jboix/pillarbox-web/), it seems that is working fine with no configuration, see the [Release](https://github.com/jboix/pillarbox-web/releases/tag/v0.6.10) that it generated.

By default it also generates and commits a CHANGELOG in the project, the changelog can be disabled by adding the option `--no-output` if desired.

**Comment by amtins** [comment]
@jboix the issue that I have is how the SemVer is handled and its consistency, a few examples: 

- [Git test](https://github.com/unjs/changelogen/blob/382eda92d13918fa5e5a354eaac04592a3fb873d/test/git.test.ts#L143) only `!` is used to create a breaking change version, you can't have a body with `BREAKING CHANGE`
- If the version is less than `1.x.x` the breaking change doesn't seem to work well
- It's also strange that, let's say the last hash commit is `cafebabe` which is available on `HEAD` and on the latest `tag`. Running `npx changelogen@latest --release` shouldn't create a new version if nothing has changed. However it generates a new version with a new tag. [GetGitDiff](https://github.com/unjs/changelogen/blob/382eda92d13918fa5e5a354eaac04592a3fb873d/src/git.ts#L62-L89) seems to behave as expected and returns an empty array when there is no diffs. In the code I see multiple issues starting from https://github.com/unjs/changelogen/blob/382eda92d13918fa5e5a354eaac04592a3fb873d/src/commands/default.ts#L44, https://github.com/unjs/changelogen/blob/382eda92d13918fa5e5a354eaac04592a3fb873d/src/git.ts#L112

That said, I absolutely love this project and how easy it is to configure and I would love to use it. Maybe we could help them fixing these minor issues. What do you think?
