### ISSUE TITLE
Investigate startup time measurements for QoS purposes

### ISSUE THREAD

**Issue by amtins** [SRGSSR/pillarbox-web#255]
**As a developer** I understand timings that can be collected during playback start for my platform.

# Acceptance criteria

- A list of reasonable time contributions to playback start is provided for further discussion with the team.

# Tasks

- [ ] Discuss common measurement rules (network, devices, streams) with the team so that we (hopefully) have comparable results.
- [ ] ...

**Comment by defagos** [comment]
Has been investigated.
